name: avotek_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  animated_text_kit: ^4.2.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets\image\svgs\onboarding.svg
    - assets\image\svgs\onboarding2.svg
    - assets\image\svgs\onboarding3.svg
    - assets\image\svgs\Pavigation.svg
    - assets\image\svgs\Pavigation2.svg
    - assets\image\svgs\Pavigation3.svg
    - assets\image\gif\Laptop.jpg
    - assets\image\svgs\Goggle.svg
    - assets\image\svgs\facebook.svg
    - assets\image\svgs\Humaaans - Space.svg
    - assets\image\gif\Hand.jpg
    - assets\image\svgs\no_video.svg
    - assets\image\svgs\no_product.svg
    - assets\image\svgs\no_notification.svg
    - assets\image\svgs\no_network.svg
    - assets\image\svgs\notify payment icon.svg
    - assets\image\svgs\notify message icon.svg
    - assets\image\svgs\Successful Icon.svg



  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Black.ttf
          weight: 900
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 700
        - asset: assets\fonts\Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Thin.ttf
          weight: 100
